version: '3.8'

services:
  mysql_db:
    image: mysql:8.0                 # Se descarga automáticamente
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      # Contraseña del root
      MYSQL_DATABASE: plataforma_educativa  # Base de datos inicial
    ports:
      - "3307:3306"                  # Puerto del host -> puerto del contenedor
    volumes:
      - mysql_data:/var/lib/mysql    # Guarda los datos persistentes
    networks:
      - plataforma-network

  redis:
    image: redis:7.2-alpine          # Se descarga automáticamente
    container_name: plataforma-redis
    ports:
      - "6379:6379"
    networks:
      - plataforma-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: plataforma-redis-commander
    ports:
      - "8083:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - plataforma-network

volumes:
  mysql_data:                        # Volumen persistente para MySQL

networks:
  plataforma-network:
    driver: bridge
